// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjqzfrogyqbhspuwmarp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcXpmcm9neXFiaHNwdXdtYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzYxMDksImV4cCI6MjA1OTQ1MjEwOX0.UYs5qB1nnHXjqwi0VHn0HGKPbujaRxOnju2-rERnolI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);