// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrapvmtyfgjhzcranvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYXB2bXR5ZmdqaHpjcmFudm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzIwNDQsImV4cCI6MjA2MDY0ODA0NH0.r9v2uyKf7cmPzbRXjR8p9cAxDreumdjEhFfmP3m0MEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);